version : 2

sources:
  - name: gz_raw_data
    schema: raw
    tables:
      - name: gz_raw_sales
        schema: sales
      - name: gz_raw_product
        schema: product
      - name: gz_raw_ship
        schema: ship